In [1]:
import os
import pandas as pd
import numpy as np
import torch_geometric
import torch
from torch_geometric.utils import to_dense_adj
from smiles_to_molecular_graphs.single_molecule_conversion import process

/usr/local/anaconda3/envs/gnn-test-env/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
os.chdir('/Users/Tom/Documents/300. MASTERS/MASTERS/THESIS/CODE/graph_neural_network_for_fuel_ignition_quality_simple/data_simplify/TB_simple_data')         
df = pd.read_csv('TB_simple_joined_all_shuffled.csv', delimiter = ';')


In [3]:
print(df['SMILES'].str.count('H').sum(),
df['SMILES'].str.count('C').sum(),
df['SMILES'].str.count('O').sum(),
df['SMILES'].str.count('F').sum(),
df['SMILES'].str.count('Cl').sum(),      
df['SMILES'].str.count('Br').sum(),
df['SMILES'].str.count('N').sum(),
df['SMILES'].str.count('S').sum())



0 760 25 391 184 0 0 0


In [4]:
print(len(df['SMILES']) - 2 - 11 - 4 -2)
print(len(df['SMILES']))

df['SMILES'].str.contains('C')

159
178


0      True
1      True
2      True
3      True
4      True
       ... 
173    True
174    True
175    True
176    True
177    True
Name: SMILES, Length: 178, dtype: bool

In [5]:
molecule  = df['SMILES'][df['SMILES'].str.contains('')]



In [6]:
data = process('CCCCl')

CCCCl


In [7]:
edge_index = data.edge_index
adjacency_matrix = to_dense_adj(edge_index)
print(edge_index)

tensor([[0, 1, 1, 2, 2, 3],
        [1, 0, 2, 1, 3, 2]])


In [13]:
print(adjacency_matrix)
print(data.x)

tensor([[[0., 1., 0., 0.],
         [1., 0., 1., 0.],
         [0., 1., 0., 1.],
         [0., 0., 1., 0.]]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
         0., 0., 0.]])


In [9]:
def remove_specified_atom_rows(file_name, new_name, atom_list):
    df = pd.read_csv('data_simplify/' + str(file_name) + '.csv', delimiter = ';')
    print(len(df))
    
    df_length = len(df)
    bool_series = pd.Series([False for i in range(df_length)])
    
    for i in range(len(atom_list)):
        loc_series = df['SMILES'].str.contains(atom_list[i])
        bool_series = bool_series | loc_series
    
    new_df = pd.DataFrame(df[~bool_series])
    
    save_spot = 'data_simplify/TB_simple_data/' + str(new_name) + '.csv'
    new_df.to_csv(save_spot, index = False, sep = ';') 
    print(len(new_df))
    
    return(new_df)


file_name_list = ['TB_train', 'TB_test', 'TB_joined_all_shuffled', 'raw', 'raw_t']
file_name_list_new = ['TB_simple_train', 'TB_simple_test', 'TB_simple_joined_all_shuffled', 'raw', 'raw_t']

for i in range(len(file_name_list)):
    remove_specified_atom_rows(file_name_list[i], file_name_list_new[i], ['H', 'Br', 'N', 'S'])
    


FileNotFoundError: [Errno 2] No such file or directory: 'data_simplify/TB_train.csv'